####################
# 全局
####################
#DeBug模式
DeBug: false
#接口密钥
ApiKey: ""
#服务器名称
Server: ""
#接口Url
Url:
  BanUser: ""
  PassVerify: ""
  Recharge: ""
  WebLogin:
    Request: ""
    Info: ""
    Success: ""
    Cancel: ""

####################
# BanUser
####################
BanUser:
  #启用
  Enable: true

####################
# PassVerify
####################
PassVerify:
  #启用
  Enable: true
  #进服时检测延迟(秒)
  TimeOut: 1
  #在服内循环检测周期(秒)
  Delay: 3

####################
# Recharge
####################
#玩家变量 {Player}
#数量变量 {NumBer}
Recharge:
  #启用
  Enable: true
  #汇率
  ExchangeRate: 1
  #充值指令
  Command: ""

####################
# WebLogin
####################
WebLogin:
  #启用
  Enable: true
  #登入链接
  Login: "https://auth.tpcraft.cn/Minecraft"