name: TPCraftPlugin
version: 1.0.0
main: cn.tpcraft.minecraft.plugin.TPCraftPlugin
api-version: 1.19
commands:
  tpcraft:
    description: TPCraft插件命令
  tpcraft help:
    description: TPCraft插件帮助
  ban:
    description: TPCraft封禁命令
  recharge add:
    description: TPCraft充值命令
  recharge exchangerate:
    description: TPCraft充值汇率查询命令